# Generated by Django 4.1.3 on 2022-12-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='news_image',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.backyardchickencoops.com.au%2Fblogs%2Flearning-centre%2F5-reasons-to-love-faverolles-chickens&psig=AOvVaw0zmsajLFZ_Kxxd9v76OeNb&ust=1670730117175000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCJizjeuQ7vsCFQAAAAAdAAAAABAE'),
            preserve_default=False,
        ),
    ]
